#!/bin/bash

set -e

if [ -z "$1" ]; then
    echo "Please provide a test file"
    exit 0
fi

testfile="$1"
filename=$(basename "$testfile" ".c")
outdir="$filename"

echo "Running test: $testfile"
echo "Basename: $filename"

mkdir -p "$filename"

cp "$testfile" "$outdir/"
pushd "$outdir"

# C to LLVMIR
c-to-llvmir $testfile $filename.ll

# Apply the transformation
PASS_ARGS="--cache-no-writeback-hint --cache-no-writeback-hint-debug"
pass-apply "$PASS_ARGS" $filename.ll $filename.o.ll

# Create a PDF of the result
llvmir2dot \
    -m war-reach-dfa-IN \
    -m hint-location \
    -m no-alias-hint-location \
    $filename.o.ll
